version: '3'
services:
  bot:
    build: .
    restart: always
    volumes:
      - ".:/code"
    depends_on:
      - rabbit
  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#      - "15672:15672"
    expose:
      - 5672
  decoder:
    build: decoder
    depends_on:
      - rabbit
    restart: always
    volumes:
      - "./decoder:/app"
      - "./Screens:/Screens"
      - "./config.py:/app/config.py"